Repository wanted-running-sheep/schedule, pull requests merged in 2022-07, with the labels that each got.

#6 [최중재] 잉그올 개인 기업 과제
  server/database/db.json
  src/@types/api.d.ts
  src/@types/enum.ts
  src/@types/styled.d.ts
  src/App.tsx
  src/api/http/httpRequest.ts
  src/api/instance/index.ts
  src/api/models/useScheduleModel.ts
  src/components/AMPMRadio.tsx
  src/components/Button.tsx
  src/components/Layout.tsx
  src/components/TimeBlock.tsx
  src/components/TimePicker/Dropdown.tsx
  src/components/TimePicker/TimePicker.tsx
  src/constants/index.ts
  src/index.tsx
  src/pages/ScheduleAddPage.tsx
  src/pages/SchedulePage.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/animation.ts
  src/styles/theme.ts
  src/utils/formatTime.ts
  src/utils/pad2Digit.ts
  src/utils/periods.ts
  src/utils/weekDays.ts
Labels: 🕹️ 기능

#11 🐛 fix: 일정추가 시 올바르게 중복체크하도록
  src/api/http/httpRequest.ts
  src/api/models/useScheduleModel.ts
  src/constants/message.ts
  src/pages/ScheduleAddPage.tsx
  src/utils/formatTime.ts
Labels: 🐞 버그

#12 ✨ feat: express 서버 구축
  backend/database/db.json
  backend/database/dbController.js
  backend/index.js
  backend/nodemon.json
  backend/package-lock.json
  backend/package.json
  backend/routes/schedule.js
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/@types/api.d.ts
  frontend/src/@types/enum.ts
  frontend/src/@types/styled.d.ts
  frontend/src/App.tsx
  frontend/src/api/http/httpRequest.ts
  frontend/src/api/instance/index.ts
  frontend/src/api/models/useScheduleModel.ts
  frontend/src/assets/css/font.css
  frontend/src/components/AMPMRadio.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/TimeBlock.tsx
  frontend/src/components/TimePicker/Dropdown.tsx
  frontend/src/components/TimePicker/TimePicker.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/message.ts
  frontend/src/index.tsx
  frontend/src/pages/ScheduleAddPage.tsx
  frontend/src/pages/SchedulePage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/styles/animation.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/media.ts
  frontend/src/styles/mixins.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/formatTime.ts
  frontend/src/utils/pad2Digit.ts
  frontend/src/utils/periods.ts
  frontend/src/utils/weekDays.ts
  frontend/tsconfig.json
  server/database/db.json
  server/index.js
Labels: 🕹️ 기능

#13 💄 style: 운영체제에 맞춰 화면이 정상적으로 보이도록 수정
  .gitignore
  frontend/src/components/@common/Button.tsx
  frontend/src/components/TimeBlock.tsx
  frontend/src/components/TimePicker/Dropdown.tsx
  frontend/src/pages/ScheduleAddPage.tsx
  frontend/src/pages/SchedulePage.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/mixins.ts
  frontend/src/styles/theme.ts
Labels: ⬆️ 리팩토링, 📱 UI

#18 💄 style: 반응형 추가
  frontend/src/components/Button.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/TimeBlock.tsx
  frontend/src/pages/ScheduleAddPage.tsx
  frontend/src/pages/SchedulePage.tsx
  frontend/src/styles/media.ts
Labels: 📱 UI

#17 ♻️ refactor: #16 메시지 상수화 및 영어로 변경
  frontend/src/api/models/useScheduleModel.ts
  frontend/src/constants/message.ts
  frontend/src/pages/ScheduleAddPage.tsx
  frontend/src/pages/SchedulePage.tsx
Labels: ⬆️ 리팩토링
